site_name: Quickwin

theme:
    logo: imgs/icon-eoap.png
    name: material

    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - search
  - mermaid2:
      version: 10.6.0

markdown_extensions:
  - pymdownx.details
  - abbr
  - admonition
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - attr_list
  - pymdownx.snippets:
      base_path: './'
  - pymdownx.highlight:
      line_spans: __span
extra_css:
  - styles/css/app.css
  
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  

nav:
  - Introduction: 'index.md'
  - Prerequisites: 
    - Introduction to YAML: prerequisites/yaml.md
    - Introduction to CWL: prerequisites/cwl.md
  - Introducing the application:
    - Water bodies detection: app/water-bodies-detection.md
    - Application Steps:
      - Water bodies detection: 
        - Description: app/water_bodies/app.md
        - Running the step: python-env/water_bodies.md
  - Package the EO Application:
    - Creating the containers: 
      - Scope: containers/scope.md
      - Build and test the container:
        - Water bodies detection: containers/water_bodies.md
    - Create CWL CommandLineTools:
      - Scope: cwl-cli/scope.md
      - Water bodies detection: cwl-cli/water_bodies.md
    - Create the CWL Workflows:
      - Scope: cwl-workflow/scope.md
      - Water bodies detection: cwl-workflow/cloud-native.md
  - Release the EO Application:
    - Scope: release/scope.md
    - Continuous Integration: release/ci.md
  - Execution Scenarios:
    - Scope: exec/scope.md
    - Running on a local machine:
      - Sentinel-2: exec/cloud-native.md 
  - Reference:
    - OGC Application Package Best Practice: reference/ogc-ap-bp.md
    - CWL CommandLineTool: reference/cwl-commandlinetool.md
    - CWL Workflow: reference/cwl-workflow.md
    - Tools: 
      - cwltool: reference/cwltool.md
